src/KoLappen/Models/Education.cs
using System;

namespace KoLappen.Models
{
    public class Education
    {
        public int EducationId { get; set; }
        public int CourseId { get; set; }
        public Course Course { get; set; }
        public int SemesterId { get; set; }
        public Semester Semester { get; set; }
        public int LocationId { get; set; }
        public Location Location { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
    }
}

src/KoLappen/Models/Semester.cs
using System.Collections.Generic;

namespace KoLappen.Models
{
    public class Semester
    {
        public int SemesterId { get; set; }
        public string SemesterName { get; set; }
        public List<Education> Education { get; set; }
    }
}

src/KoLappen/Controllers/EducationController.cs
using KoLappen.Models;
using KoLappen.ViewModels;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KoLappen.Controllers
{
    public class EducationController : Controller
    {
        DBContext dbContext;
        IProfileRepository profileDataManager;
        IEducationRepository educationRepository;

        public EducationController(
            DBContext dbContext,
            IAccountRepository accountRepository,
            IProfileRepository profileDataManager,
            IEducationRepository educationRepository
            )
        {
            this.dbContext = dbContext;
            this.profileDataManager = profileDataManager;
            this.educationRepository = educationRepository;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        //public IActionResult Semester()
        //{
        //    return View();
        //}
        public IActionResult Alumner()
        {
            var viewModel = educationRepository.GetAllCourses();
            return View(viewModel);
        }


        public IActionResult Semester(int id)
        {
            var viewModel = educationRepository.GetAllSemesters(id);
            return View(viewModel);
        }


        [Route("education/course/{courseId:int}/sem/{semesterId:int}")]
        public IActionResult Katalog(int semesterId, int courseId)
        {
            var viewModel = profileDataManager.GetOneClass(semesterId, courseId);
            return View(viewModel);
        }

        [Authorize]
        public ActionResult AddEducation()
        {
            var model = educationRepository.GetRegisterEducationOptions();
            return View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult AddEducation(AddEducationVM viewModel)
        {
            if (!ModelState.IsValid)    // kollar valideringen, returnerar ErrorMsges
            {
                return View(viewModel);
            }

            educationRepository.AddEducation(viewModel);

            return RedirectToAction(nameof(EducationController.AddEducation), "education");

            //return View(viewModel);
        }

        [Authorize]
        public ActionResult AddCourse()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult AddCourse(AddEducationVM viewModel)
        {
            if (!ModelState.IsValid)    // kollar valideringen, returnerar ErrorMsges
            {
                return View(viewModel);
            }

            educationRepository.AddCourse(viewModel);

            return RedirectToAction(nameof(EducationController.AddEducation), "education");
        }

        [Authorize]
        public ActionResult AddSemester()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult AddSemester(AddEducationVM viewModel)
        {
            if (!ModelState.IsValid)    // kollar valideringen, returnerar ErrorMsges
            {
                return View(viewModel);
            }

            educationRepository.AddSemester(viewModel);

            return RedirectToAction(nameof(EducationController.AddEducation), "education");
        }

        [Authorize]
        public ActionResult AddLocation()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult AddLocation(AddEducationVM viewModel)
        {
            if (!ModelState.IsValid)    // kollar valideringen, returnerar ErrorMsges
            {
                return View(viewModel);
            }

            educationRepository.AddLocation(viewModel);

            return RedirectToAction(nameof(EducationController.AddEducation), "education");
        }
    }
}

src/KoLappen/Views/Education/AddCourse.cshtml
@model KoLappen.ViewModels.AddEducationVM
@addTagHelper"*, Microsoft.AspNet.Mvc.TagHelpers"

@{
    ViewBag.Title = "Lägga till utbildning";
}

<form asp-controller="Education" asp-action="AddCourse">
    <div class="row">
        <div class="col-md-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Skapa kurs</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-10">
                            <label asp-for="CourseName"></label>
                            <input asp-for="CourseName" class="form-control custom" placeholder="Kurs namn" />
                            <span asp-validation-for="CourseName"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-5">
            <button type="submit" value="Education" class="btn btn-success">Registrera kurs</button>
        </div>
    </div>
</form>

src/KoLappen/Views/Education/AddCourseOld.cshtml
@model KoLappen.ViewModels.AddEducationVM
@addTagHelper"*, Microsoft.AspNet.Mvc.TagHelpers"

@{
    Layout = null;
}


<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Registrera kurs</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="~/css/kolappen.css" rel="stylesheet" />

</head>
<body>
    <div style="background-image: url(../images/academicwork_background2.jpg); background-position: 50% 50%;">
        <header class="mainHeader">
            <img src="http://academy.academicwork.se/wp-content/uploads/2016/02/Academy_250x100.png" />
        </header>
        <section class="loginimg">
            <center>
                <form asp-controller="Education" asp-action="AddCourse">                                        
                    @*<label asp-for="CourseName"></label>
                    <input asp-for="CourseName" class="form-control custom" placeholder="Kurs namn" />
                    <span asp-validation-for="CourseName"></span>
                    <br />
                    <label asp-for="Semester"></label>
                    <input asp-for="Semester" class="form-control custom" placeholder="Termin" />
                    <span asp-validation-for="Semester"></span>
                    <br />
                    <label asp-for="Location"></label>
                    <input asp-for="Location" class="form-control custom" placeholder="Plats" />
                    <span asp-validation-for="Location"></span>
                    <br />*@
                    <br />
                    @Html.LabelFor(m => m.CourseName)
                    @Html.DropDownListFor(m => m.CourseName, Model.Courses)
                    <br />
                    @Html.LabelFor(m => m.SemesterName)
                    @Html.DropDownListFor(m => m.SemesterName, Model.Semesters)                   
                    <br />
                    @Html.LabelFor(m => m.LocationName)
                    @Html.DropDownListFor(m => m.LocationName, Model.Locations)
                    <br />
                    <button type="submit" value="Register" class="btn btn-success">Registrera</button>
                </form>
            </center>
        </section>
    </div>
    <footer class="mainFooter">
        <p>HOME OF THE YOUNG PROFESSIONALS</p>
    </footer>
</body>
</html>

src/KoLappen/Views/Education/AddEducation.cshtml
@model KoLappen.ViewModels.AddEducationVM
@addTagHelper"*, Microsoft.AspNet.Mvc.TagHelpers"

@{
    ViewBag.Title = "Lägga till utbildning";
}
<div class="row">
    <div class="col-md-6">
        <div class="row">
            <form asp-controller="Education" asp-action="AddEducation">
                <div class="col-md-10">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Registrera utbildning</h3>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-xs-10">
                                    <label asp-for="CourseName"></label>
                                    <select class="form-control" data-val="true" data-val-required="V&#xE4;lj kurs." id="CourseName" name="CourseName">
                                        @foreach (var course in Model.Courses)
                                        {
                                            <option value="@course.Value">@course.Text</option>
                                        }
                                    </select>
                                    <br />
                                    <label asp-for="SemesterName"></label>
                                    <select class="form-control" data-val="true" data-val-required="V&#xE4;lj termin." id="SemesterName" name="SemesterName">
                                        @foreach (var semester in Model.Semesters)
                                        {
                                            <option value="@semester.Value">@semester.Text</option>
                                        }
                                    </select>
                                    <br />
                                    <label asp-for="LocationName"></label>
                                    <select class="form-control" data-val="true" data-val-required="V&#xE4;lj stad." id="LocationName" name="LocationName">
                                        @foreach (var location in Model.Locations)
                                        {
                                            <option value="@location.Value">@location.Text</option>
                                        }
                                    </select>
                                    <br />
                                    <button type="submit" value="Education" class="btn btn-success">Registrera utbildning</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <form asp-controller="Education" asp-action="AddCourse">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Registrera kurs</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-10">
                            <label asp-for="CourseName"></label>
                            <input asp-for="CourseName" class="form-control custom" placeholder="Kurs namn" />
                            <input asp-for="SemesterName" type="hidden" class="form-control custom" placeholder="Termin" value="null" />
                            <input asp-for="LocationName" type="hidden" class="form-control custom" placeholder="Stad" value="null" />
                            <span asp-validation-for="CourseName"></span>
                            <br />
                            <button type="submit" value="Education" class="btn btn-success">Registrera kurs</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-3">
        <form asp-controller="Education" asp-action="AddSemester">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Registrera Termin</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-10">
                            <label asp-for="SemesterName"></label>
                            <input asp-for="SemesterName" class="form-control custom" placeholder="Termin" />
                            <input asp-for="CourseName" type="hidden" class="form-control custom" placeholder="Kurs" value="null" />
                            <input asp-for="LocationName" type="hidden" class="form-control custom" placeholder="Stad" value="null" />

                            <span asp-validation-for="SemesterName"></span>
                            <br />
                            <button type="submit" value="Education" class="btn btn-success">Registrera termin</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-3">
        <form asp-controller="Education" asp-action="AddLocation">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Registrera stad</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-10">
                            <label asp-for="LocationName"></label>
                            <input asp-for="LocationName" class="form-control custom" placeholder="Stad namn" />
                            <input asp-for="SemesterName" type="hidden" class="form-control custom" placeholder="Termin" value="null" />
                            <input asp-for="CourseName" type="hidden" class="form-control custom" placeholder="Kurs" value="null" />
                            <span asp-validation-for="LocationName"></span>
                            <br />
                            <button type="submit" value="Education" class="btn btn-success">Registrera stad</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

src/KoLappen/Views/Education/Alumner.cshtml
@using KoLappen.ViewModels
@model AlumnerVM[]
@addTagHelper"*, Microsoft.AspNet.Mvc.TagHelpers"

<h2 style="color:#00aa3c">ALUMNER</h2>
<h3 style="color:#00aa3c">KURSER</h3>

    @*@foreach (var item in Model)
    {
        <td>@item.education</td>
    }
    *@

<div class="alumner">
    @*<p><b><a href="@Url.Action("Semester", "Account", new { id = 1 })" style="color:#00aa3c">test</a></b></p>*@
    
    @*<p><b><a href="/Account/Semester/1" style="color:#00aa3c">C#</a></b></p>
    <p><b><a href="/Account/Semester/2" style="color:#00aa3c">JAVA</a></b></p>
    <p><b><a href="/Account/Semester/3" style="color:#00aa3c">Försäljning</a></b></p>*@

    @foreach (var item in Model)
    {
        @*<h2>@item.CourseName</h2>*@
        @*<p><b><a href="/Account/Semester/@item.CourseID" style="color:#00aa3c">utan asp @item.CourseName</a></b></p>*@


        <p><b><a asp-controller="Education" asp-action="Semester" asp-route-id="@item.CourseID" style="color:#00aa3c">@item.CourseName</a></b></p>
    }
</div>

src/KoLappen/Views/Education/Katalog.cshtml
@model List<ProfileVM>


    @*<div class="avatar-flip">
        <img src="http://media.idownloadblog.com/wp-content/uploads/2012/04/Phil-Schiller-headshot-e1362692403868.jpg" height="150" width="150">
        <img src="http://i1112.photobucket.com/albums/k497/animalsbeingdicks/abd-3-12-2015.gif~original" height="150" width="150">
    </div>*@
    @foreach (var item in Model)
    {
        <div class="col-md-1"></div>
        <div class="container col-md-3">
            <div class="avatar-flip">
                <img src="@item.Image" height="150" width="150">
                <img src="http://i1112.photobucket.com/albums/k497/animalsbeingdicks/abd-3-12-2015.gif~original" height="150" width="150">
            </div>

            <h2>@item.EducationName</h2>
            <h2>@item.SemesterName</h2>

            <h4>@item.Name</h4>
            <h4>@item.LastName</h4>
            <h4>@item.Email</h4>
            <h4>@item.PhoneNumber</h4>
            <h4>@item.UserJobLocation</h4>

        </div>
    }
    @*<h4>C# Utvecklare</h4>
    <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Maecenas sed diam eget risus varius blandit sit amet non magna ip sum dolore.</p>
    <p>Connec dolore ipsum faucibus mollis interdum. Donec ullamcorper nulla non metus auctor fringilla.</p>*@



<div class="col-md-1"></div>
<div class="container col-md-3">
    <div class="avatar-flip">
        <img src="http://media.idownloadblog.com/wp-content/uploads/2012/04/Phil-Schiller-headshot-e1362692403868.jpg" height="150" width="150">
        <img src="http://i1112.photobucket.com/albums/k497/animalsbeingdicks/abd-3-12-2015.gif~original" height="150" width="150">
    </div>
    <h2>John Smith</h2>
    <h4>C# Utvecklare</h4>
    <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Maecenas sed diam eget risus varius blandit sit amet non magna ip sum dolore.</p>
    <p>Connec dolore ipsum faucibus mollis interdum. Donec ullamcorper nulla non metus auctor fringilla.</p>
</div>

src/KoLappen/Views/Education/Semester.cshtml
@model AlumnerVM[]

<h2 style="color:#00aa3c">ALUMNER</h2>
<h3 style="color:#00aa3c">TERMIN</h3>

@*@foreach (var item in Model)
    {
        <td>@item.education</td>
    }
*@

<div class="alumner">
    
    @*<p><b><a href="@Url.Action("Katalog", "Account", new { id = 1 })" style="color:#00aa3c">test</a></b></p>*@
    
    @foreach (var item in Model)
    {
        @*<p><b><a href="/Account/Katalog/@item.CourseID" style="color:#00aa3c">@item.Semester</a></b></p>*@
        <p><b><a asp-controller="Education" asp-action="Katalog" asp-route-semesterId="@item.SemesterId" asp-route-courseId="@item.CourseID" style="color:#00aa3c">@item.Semester</a></b></p>
    }
   
    @*<p><b><a href="/Account/Katalog/2" style="color:#00aa3c">VT 16</a></b></p>
    <p><b><a href="/Account/Katalog/3" style="color:#00aa3c">Sommar 16</a></b></p>
    <p><b><a href="/Account/Katalog/12" style="color:#00aa3c">C++</a></b></p>*@
</div>